// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyColTmK_4cclw65Nuh3o1Rf2LP-BCWget8',
    appId: '1:838321152874:web:c9f2a773b77320095dbb13',
    messagingSenderId: '838321152874',
    projectId: 'flutterproject-4580b',
    authDomain: 'flutterproject-4580b.firebaseapp.com',
    storageBucket: 'flutterproject-4580b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3G8bSTP0IKJ7kQyDVZ6VBMlbHLv-FL_A',
    appId: '1:838321152874:android:92125e25ab6d46ac5dbb13',
    messagingSenderId: '838321152874',
    projectId: 'flutterproject-4580b',
    storageBucket: 'flutterproject-4580b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9QcEb699pB6lvnxcBtvNoTsHQEoibEL8',
    appId: '1:838321152874:ios:1b473b4deca3c47a5dbb13',
    messagingSenderId: '838321152874',
    projectId: 'flutterproject-4580b',
    storageBucket: 'flutterproject-4580b.appspot.com',
    iosClientId: '838321152874-tnr3h7jbn8unfe2q8ktag8bh64eg8g25.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9QcEb699pB6lvnxcBtvNoTsHQEoibEL8',
    appId: '1:838321152874:ios:a477c964bf8fa8f35dbb13',
    messagingSenderId: '838321152874',
    projectId: 'flutterproject-4580b',
    storageBucket: 'flutterproject-4580b.appspot.com',
    iosClientId: '838321152874-bs8bq6550d3eg7tmi6h2roei4fhl975u.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseauth.RunnerTests',
  );
}
